# Generated by Django 2.2.7 on 2019-11-20 07:20

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191120_1545'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotravel',
            name='categorylarge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CLarge'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='categorymedium',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='categorylarge', chained_model_field='categorylarge', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CMedium'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='categorysmall',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='categorymedium', chained_model_field='categorymedium', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CSmall'),
        ),
    ]
