# Generated by Django 2.2.7 on 2019-11-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20191120_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infotravel',
            name='category',
        ),
    ]
