# Generated by Django 2.2.7 on 2019-11-25 01:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_remove_infotravel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpname', models.CharField(max_length=40, null=True, verbose_name='Name')),
                ('tpcomment', models.CharField(max_length=64, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'TravelPlan',
                'verbose_name_plural': 'TravelPlan',
                'db_table': 'travelplan',
            },
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='part',
            field=models.CharField(choices=[('Eat', '먹다'), ('Drink', '마시다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], max_length=64, verbose_name='구분'),
        ),
        migrations.CreateModel(
            name='POIpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=40, null=True, verbose_name='Name')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('travelplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.TravelPlan', verbose_name='TravelPlan')),
            ],
            options={
                'verbose_name': 'POIpoint',
                'verbose_name_plural': 'POIpoint',
                'db_table': 'poipoint',
            },
        ),
    ]
