# Generated by Django 2.2.7 on 2019-11-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20191125_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotravel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.City', verbose_name='City'),
        ),
    ]
