# Generated by Django 2.2.7 on 2019-11-29 01:00

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('travels', '0005_auto_20191126_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCurator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=128, null=True, verbose_name='제목(한국어)')),
                ('titleeng', models.CharField(max_length=128, null=True, verbose_name='제목(영어)')),
                ('titleven', models.CharField(max_length=128, null=True, verbose_name='제목(베트남어)')),
                ('created', models.DateField(null=True, verbose_name='Created')),
                ('writter', models.CharField(max_length=64, verbose_name='Writter')),
                ('introko', models.TextField(blank=True, help_text='이곳을 소개해 주세요.', null=True, verbose_name='여행정보(한국어)')),
                ('introeng', models.TextField(blank=True, help_text='이곳을 소개해 주세요.', null=True, verbose_name='여행정보(영어)')),
                ('introven', models.TextField(blank=True, help_text='이곳을 소개해 주세요.', null=True, verbose_name='여행정보(베트남어)')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.City', verbose_name='City')),
                ('infotravel', models.ManyToManyField(to='travels.InfoTravel', verbose_name='여행장소 추가')),
                ('tageng', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='travels.SecondTaggedItem', to='travels.SecondTag', verbose_name='태그(영어)')),
                ('tagko', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)')),
                ('tagven', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='travels.ThirdTaggedItem', to='travels.ThirdTag', verbose_name='태그(베트남어)')),
            ],
            options={
                'verbose_name': 'TravelCurator',
                'verbose_name_plural': 'TravelCurators',
                'db_table': 'travelcurator',
            },
        ),
        migrations.CreateModel(
            name='TCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcimg', models.ImageField(upload_to='', verbose_name='Trave Image')),
                ('travelcurator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.TravelCurator', verbose_name='TravelCurator')),
            ],
            options={
                'verbose_name': '대표이미지(TravelCulator)',
                'verbose_name_plural': '대표이미지(TravelCulator)',
                'db_table': 'tcimage',
            },
        ),
    ]
