# Generated by Django 2.2.7 on 2019-11-29 01:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('travels', '0006_tcimage_travelcurator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poipoint',
            options={'verbose_name': '여행코스', 'verbose_name_plural': '여행코스'},
        ),
        migrations.RemoveField(
            model_name='poipoint',
            name='pname',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='tpcomment',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='tpname',
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='pnameeng',
            field=models.CharField(max_length=40, null=True, verbose_name='장소명(영어)'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='pnameko',
            field=models.CharField(max_length=40, null=True, verbose_name='장소명(한국어)'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='pnameven',
            field=models.CharField(max_length=40, null=True, verbose_name='장소명(베트남어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='course',
            field=models.IntegerField(choices=[(1, '1시간'), (2, '반나절'), (3, '하루')], default=1, verbose_name='코스선택'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='courseinfoeng',
            field=models.TextField(blank=True, help_text='코스를 소개해 주세요.', null=True, verbose_name='코스정보(영어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='courseinfoko',
            field=models.TextField(blank=True, help_text='코스를 소개해 주세요.', null=True, verbose_name='코스정보(한국어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='courseinfoven',
            field=models.TextField(blank=True, help_text='코스를 소개해 주세요.', null=True, verbose_name='코스정보(베트남어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='created',
            field=models.DateField(null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='tageng',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='travels.SecondTaggedItem', to='travels.SecondTag', verbose_name='태그(영어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='tagven',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='travels.ThirdTaggedItem', to='travels.ThirdTag', verbose_name='태그(베트남어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='titleeng',
            field=models.CharField(max_length=128, null=True, verbose_name='소개타이틀(영어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='titleko',
            field=models.CharField(max_length=128, null=True, verbose_name='소개타이틀(한국어)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='titleven',
            field=models.CharField(max_length=128, null=True, verbose_name='소개타이틀(베트남어)'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='위치'),
        ),
    ]
