# Generated by Django 2.2.7 on 2019-12-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_auto_20191129_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menueng',
            field=models.CharField(max_length=64, verbose_name='대표메뉴(영어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menuko',
            field=models.CharField(max_length=64, verbose_name='대표메뉴(한국어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menuven',
            field=models.CharField(max_length=64, verbose_name='대표메뉴(베트남어)'),
        ),
    ]
