# Generated by Django 2.2.7 on 2019-12-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_auto_20191204_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infotravel',
            options={'verbose_name': 'TripGuide', 'verbose_name_plural': 'TripGuide'},
        ),
        migrations.AlterModelOptions(
            name='travelcurator',
            options={'verbose_name': 'TripCurator', 'verbose_name_plural': 'TripCurators'},
        ),
        migrations.AlterModelOptions(
            name='travelplan',
            options={'verbose_name': 'TravelCourse', 'verbose_name_plural': 'TravelCourse'},
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='part',
            field=models.CharField(choices=[('Eat', '먹다'), ('Drink', '마시다'), ('Fun', '놀다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], max_length=64, verbose_name='구분'),
        ),
        migrations.CreateModel(
            name='FunPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biztimeko', models.CharField(max_length=64, verbose_name='영업시간(한국어)')),
                ('biztimeeng', models.CharField(max_length=64, verbose_name='영업시간(영어)')),
                ('biztimeven', models.CharField(max_length=64, verbose_name='영업시간(베트남어)')),
                ('programko', models.CharField(max_length=64, verbose_name='프로그램(한국어)')),
                ('programeng', models.CharField(max_length=64, verbose_name='프로그램(영어)')),
                ('programven', models.CharField(max_length=64, verbose_name='프로그램(베트남어)')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travels.InfoTravel')),
            ],
        ),
    ]
