# Generated by Django 2.2.7 on 2019-12-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_auto_20191205_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buypart',
            name='biztimeeng',
            field=models.CharField(max_length=128, verbose_name='영업시간(영어)'),
        ),
        migrations.AlterField(
            model_name='buypart',
            name='biztimeko',
            field=models.CharField(max_length=128, verbose_name='영업시간(한국어)'),
        ),
        migrations.AlterField(
            model_name='buypart',
            name='biztimeven',
            field=models.CharField(max_length=128, verbose_name='영업시간(베트남어)'),
        ),
        migrations.AlterField(
            model_name='buypart',
            name='saleitemseng',
            field=models.CharField(max_length=128, verbose_name='판매상품(영어)'),
        ),
        migrations.AlterField(
            model_name='buypart',
            name='saleitemsko',
            field=models.CharField(max_length=128, verbose_name='판매상품(한국어)'),
        ),
        migrations.AlterField(
            model_name='buypart',
            name='saleitemsven',
            field=models.CharField(max_length=128, verbose_name='판매상품(베트남어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='biztimeeng',
            field=models.CharField(max_length=128, verbose_name='영업시간(영어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='biztimeko',
            field=models.CharField(max_length=128, verbose_name='영업시간(한국어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='biztimeven',
            field=models.CharField(max_length=128, verbose_name='영업시간(베트남어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menueng',
            field=models.CharField(max_length=128, verbose_name='대표메뉴(영어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menuko',
            field=models.CharField(max_length=128, verbose_name='대표메뉴(한국어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menuven',
            field=models.CharField(max_length=128, verbose_name='대표메뉴(베트남어)'),
        ),
        migrations.AlterField(
            model_name='funpart',
            name='biztimeeng',
            field=models.CharField(max_length=128, verbose_name='영업시간(영어)'),
        ),
        migrations.AlterField(
            model_name='funpart',
            name='biztimeko',
            field=models.CharField(max_length=128, verbose_name='영업시간(한국어)'),
        ),
        migrations.AlterField(
            model_name='funpart',
            name='biztimeven',
            field=models.CharField(max_length=128, verbose_name='영업시간(베트남어)'),
        ),
        migrations.AlterField(
            model_name='funpart',
            name='programeng',
            field=models.CharField(max_length=128, verbose_name='프로그램(영어)'),
        ),
        migrations.AlterField(
            model_name='funpart',
            name='programko',
            field=models.CharField(max_length=128, verbose_name='프로그램(한국어)'),
        ),
        migrations.AlterField(
            model_name='funpart',
            name='programven',
            field=models.CharField(max_length=128, verbose_name='프로그램(베트남어)'),
        ),
        migrations.AlterField(
            model_name='seepart',
            name='operationtimeeng',
            field=models.CharField(max_length=128, verbose_name='운영시간(영어)'),
        ),
        migrations.AlterField(
            model_name='seepart',
            name='operationtimeko',
            field=models.CharField(max_length=128, verbose_name='운영시간(한국어)'),
        ),
        migrations.AlterField(
            model_name='seepart',
            name='operationtimeven',
            field=models.CharField(max_length=128, verbose_name='운영시간(베트남어)'),
        ),
        migrations.AlterField(
            model_name='sleeppart',
            name='inclusioneng',
            field=models.CharField(max_length=128, verbose_name='포함사항(영어)'),
        ),
        migrations.AlterField(
            model_name='sleeppart',
            name='inclusionko',
            field=models.CharField(max_length=128, verbose_name='포함사항(한국어)'),
        ),
        migrations.AlterField(
            model_name='sleeppart',
            name='inclusionven',
            field=models.CharField(max_length=128, verbose_name='포함사항(베트남어)'),
        ),
        migrations.AlterField(
            model_name='sleeppart',
            name='roomtypeeng',
            field=models.CharField(max_length=128, verbose_name='객실타입(영어)'),
        ),
        migrations.AlterField(
            model_name='sleeppart',
            name='roomtypeko',
            field=models.CharField(max_length=128, verbose_name='객실타입(한국어)'),
        ),
        migrations.AlterField(
            model_name='sleeppart',
            name='roomtypeven',
            field=models.CharField(max_length=128, verbose_name='객실타입(베트남어)'),
        ),
    ]
