# Generated by Django 2.2.7 on 2019-12-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_auto_20191205_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotravel',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture10'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture5'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture6'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture7'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture8'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture9'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture1'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture3'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture4'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture1'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture3'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture4'),
        ),
    ]
