# Generated by Django 2.2.7 on 2019-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_auto_20191205_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotravel',
            name='asset',
            field=models.CharField(choices=[('M', '자산'), ('N', '공용')], max_length=64, null=True, verbose_name='정보형태'),
        ),
    ]
