# Generated by Django 2.2.7 on 2019-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_infotravel_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture2'),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture3'),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture4'),
        ),
    ]
