# Generated by Django 2.2.7 on 2019-12-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_auto_20191205_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.City', verbose_name='City'),
        ),
    ]
