# Generated by Django 2.2.7 on 2019-12-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0015_auto_20191206_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='travels.City', verbose_name='City'),
        ),
    ]
