# Generated by Django 2.2.7 on 2019-12-12 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0016_auto_20191206_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infotravel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.InfoTravel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'infotravel')},
            },
        ),
        migrations.AddField(
            model_name='infotravel',
            name='like_infotravel',
            field=models.ManyToManyField(blank=True, related_name='like_infotravel', through='travels.Likeit', to=settings.AUTH_USER_MODEL),
        ),
    ]
