# Generated by Django 2.2.7 on 2019-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_auto_20191212_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('nameko',), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Logo-Image'),
        ),
        migrations.AddField(
            model_name='city',
            name='nameeng',
            field=models.CharField(default=None, max_length=64, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='city',
            name='nameko',
            field=models.CharField(default=None, max_length=64, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='city',
            name='nameven',
            field=models.CharField(default=None, max_length=64, verbose_name='Name'),
        ),
    ]
