# Generated by Django 2.2.7 on 2019-12-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0021_auto_20191213_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='nameko',
            field=models.CharField(default='', max_length=64, verbose_name='Name(한국어)'),
        ),
    ]
