# Generated by Django 2.2.7 on 2019-12-13 11:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0022_auto_20191213_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='it_tag', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
        migrations.AlterField(
            model_name='travelcurator',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tc_tag', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tp_tag', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
    ]
