# Generated by Django 2.2.7 on 2019-12-13 11:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0023_auto_20191213_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
        migrations.AlterField(
            model_name='travelcurator',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
    ]
