# Generated by Django 2.2.7 on 2019-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0027_city_gotocity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='gotocity',
            field=models.PositiveIntegerField(choices=[(1, 'Seoul'), (2, 'Busan')], null=True, verbose_name='Select City'),
        ),
    ]
