# Generated by Django 2.2.7 on 2019-12-31 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0028_auto_20191217_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.InfoTravel'),
        ),
    ]
