# Generated by Django 2.2.7 on 2019-12-31 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0029_auto_20191231_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travels.InfoTravel'),
        ),
    ]
