# Generated by Django 2.2.7 on 2020-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0030_auto_20191231_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='course',
            field=models.CharField(choices=[('One-Hours', '1시간'), ('Half-Day', '반나절'), ('One-Day', '하루')], default=1, max_length=64, verbose_name='코스선택'),
        ),
    ]
