# Generated by Django 2.2.7 on 2020-01-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0031_auto_20200105_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='titleeng',
            field=models.CharField(max_length=512, verbose_name='소개타이틀(영어)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='titleko',
            field=models.CharField(max_length=512, verbose_name='소개타이틀(한국어)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='titleven',
            field=models.CharField(max_length=512, verbose_name='소개타이틀(베트남어)'),
        ),
    ]
