# Generated by Django 2.2.7 on 2020-01-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0032_auto_20200105_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='titleeng',
            field=models.TextField(help_text='이곳을 소개해 주세요.', verbose_name='소개타이틀(영어)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='titleko',
            field=models.TextField(help_text='이곳을 소개해 주세요.', verbose_name='소개타이틀(한국어)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='titleven',
            field=models.TextField(help_text='이곳을 소개해 주세요.', verbose_name='소개타이틀(베트남어)'),
        ),
    ]
