# Generated by Django 2.2.7 on 2020-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0035_auto_20200110_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='typeit',
            field=models.IntegerField(choices=[(1, 'Must See'), (2, 'Hot'), (3, 'Normal')], verbose_name='유형선택'),
        ),
    ]
