# Generated by Django 2.2.7 on 2020-01-15 08:38

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0036_auto_20200114_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='categorylarge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorylarge', to='common.CLarge'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='categorymedium',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='categorylarge', chained_model_field='categorylarge', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymedium', to='common.CMedium'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='categorysmall',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='categorymedium', chained_model_field='categorymedium', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorysmall', to='common.CSmall'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='tageng',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='tageng', through='travels.SecondTaggedItem', to='travels.SecondTag', verbose_name='태그(영어)'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='tagko',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='tagko', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='tagven',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='tagven', through='travels.ThirdTaggedItem', to='travels.ThirdTag', verbose_name='태그(베트남어)'),
        ),
    ]
