# Generated by Django 2.2.7 on 2020-01-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0037_auto_20200115_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeit',
            name='infotravel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeits', to='travels.InfoTravel'),
        ),
    ]
