# Generated by Django 2.2.7 on 2020-03-25 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20200325_1342'),
        ('travels', '0038_auto_20200123_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypart',
            name='pin',
            field=models.ManyToManyField(to='common.PinBuy', verbose_name='사다 핀'),
        ),
        migrations.AddField(
            model_name='funpart',
            name='pin',
            field=models.ManyToManyField(to='common.PinFun', verbose_name='놀다 핀'),
        ),
        migrations.CreateModel(
            name='EatPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biztimeko', models.CharField(max_length=128, verbose_name='영업시간(한국어)')),
                ('biztimeeng', models.CharField(max_length=128, verbose_name='영업시간(영어)')),
                ('biztimeven', models.CharField(max_length=128, verbose_name='영업시간(베트남어)')),
                ('menuko', models.CharField(max_length=128, verbose_name='대표메뉴(한국어)')),
                ('menueng', models.CharField(max_length=128, verbose_name='대표메뉴(영어)')),
                ('menuven', models.CharField(max_length=128, verbose_name='대표메뉴(베트남어)')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travels.InfoTravel')),
                ('pin', models.ManyToManyField(to='common.PinEat', verbose_name='먹다 핀')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biztimeko', models.CharField(max_length=128, verbose_name='영업시간(한국어)')),
                ('biztimeeng', models.CharField(max_length=128, verbose_name='영업시간(영어)')),
                ('biztimeven', models.CharField(max_length=128, verbose_name='영업시간(베트남어)')),
                ('menuko', models.CharField(max_length=128, verbose_name='대표메뉴(한국어)')),
                ('menueng', models.CharField(max_length=128, verbose_name='대표메뉴(영어)')),
                ('menuven', models.CharField(max_length=128, verbose_name='대표메뉴(베트남어)')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travels.InfoTravel')),
                ('pin', models.ManyToManyField(to='common.PinDrink', verbose_name='마시다 핀')),
            ],
        ),
    ]
