# Generated by Django 2.2.7 on 2020-03-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0041_auto_20200325_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='writer',
            field=models.CharField(default='', max_length=64, verbose_name='Writter'),
        ),
    ]
