# Generated by Django 2.2.7 on 2020-03-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0020_auto_20200325_1716'),
        ('travels', '0042_travelplan_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=64, null=True, verbose_name='숙소명')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_data', models.DateTimeField(null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.City', verbose_name='City')),
                ('pinbuy', models.ManyToManyField(to='common.PinBuy', verbose_name='사다 핀')),
                ('pindrink', models.ManyToManyField(to='common.PinDrink', verbose_name='마시다 핀')),
                ('pineat', models.ManyToManyField(to='common.PinEat', verbose_name='먹다 핀')),
                ('pinfun', models.ManyToManyField(to='common.PinFun', verbose_name='놀다 핀')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '여행계획',
                'verbose_name_plural': '여행계획',
                'db_table': 'tourplan',
            },
        ),
    ]
