# Generated by Django 2.2.7 on 2020-03-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0043_tourplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourplan',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
