# Generated by Django 2.2.7 on 2020-03-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0044_auto_20200326_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourplan',
            options={'verbose_name': 'TourPlan', 'verbose_name_plural': 'TourPlan'},
        ),
        migrations.AddField(
            model_name='tourplan',
            name='pickit',
            field=models.ManyToManyField(to='travels.InfoTravel', verbose_name='InfoTravel'),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='picktp',
            field=models.ManyToManyField(to='travels.TravelPlan', verbose_name='TravelPlan'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
