# Generated by Django 2.2.7 on 2020-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0045_auto_20200330_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplan',
            name='picktp',
            field=models.ManyToManyField(to='travels.TravelPlan', verbose_name='TravelPlan(Trip Culator)'),
        ),
    ]
