# Generated by Django 2.2.7 on 2020-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0047_auto_20200406_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplan',
            name='pickit',
            field=models.ManyToManyField(to='travels.InfoTravel', verbose_name='InfoTravel'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='picktp',
            field=models.ManyToManyField(to='travels.TravelPlan', verbose_name='TravelPlan(Trip Culator)'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pinbuy',
            field=models.ManyToManyField(to='common.PinBuy', verbose_name='사다 핀'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pindrink',
            field=models.ManyToManyField(to='common.PinDrink', verbose_name='마시다 핀'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pineat',
            field=models.ManyToManyField(to='common.PinEat', verbose_name='먹다 핀'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pinfun',
            field=models.ManyToManyField(to='common.PinFun', verbose_name='놀다 핀'),
        ),
    ]
