# Generated by Django 2.2.7 on 2020-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0048_auto_20200406_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplan',
            name='pickit',
            field=models.ManyToManyField(blank=True, related_name='pickit', to='travels.InfoTravel', verbose_name='InfoTravel'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='picktp',
            field=models.ManyToManyField(blank=True, related_name='picktp', to='travels.TravelPlan', verbose_name='TravelPlan(Trip Culator)'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pinbuy',
            field=models.ManyToManyField(blank=True, related_name='pinbuy', to='common.PinBuy', verbose_name='사다 핀'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pindrink',
            field=models.ManyToManyField(blank=True, related_name='pindrink', to='common.PinDrink', verbose_name='마시다 핀'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pineat',
            field=models.ManyToManyField(blank=True, related_name='pineat', to='common.PinEat', verbose_name='먹다 핀'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='pinfun',
            field=models.ManyToManyField(blank=True, related_name='pinfun', to='common.PinFun', verbose_name='놀다 핀'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='writer',
            field=models.CharField(default='', max_length=64, verbose_name='Writer'),
        ),
    ]
