# Generated by Django 2.2.7 on 2020-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0049_auto_20200410_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('id',), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='tourplan',
            name='pic_url',
            field=models.CharField(max_length=128, null=True, verbose_name='배경이미지'),
        ),
    ]
