# Generated by Django 2.2.7 on 2020-05-13 02:24

import backendapp.travels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0051_auto_20200510_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poipoint',
            options={'ordering': ('id',), 'verbose_name': '여행코스', 'verbose_name_plural': '여행코스'},
        ),
        migrations.AddField(
            model_name='travelplan',
            name='infotravel',
            field=models.ManyToManyField(to='travels.InfoTravel', verbose_name='여행장소 추가'),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.city_directory_path, verbose_name='Picture1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.city_directory_path, verbose_name='Picture2'),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.city_directory_path, verbose_name='Picture3'),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.city_directory_path, verbose_name='Picture4'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture1',
            field=models.ImageField(default='', upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture1'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture10'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture2'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture3'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture4'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture5'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture6'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture7'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture8'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.infotravel_directory_path, verbose_name='Picture9'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.travelplan_directory_path, verbose_name='Picture1'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.travelplan_directory_path, verbose_name='Picture2'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.travelplan_directory_path, verbose_name='Picture3'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to=backendapp.travels.models.travelplan_directory_path, verbose_name='Picture4'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='ptitleeng',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='설명(영어)'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='ptitleko',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='설명(한국어)'),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='ptitleven',
            field=models.CharField(blank=True, max_length=4256, null=True, verbose_name='설명(베트남어)'),
        ),
    ]
