# Generated by Django 2.2.7 on 2019-12-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
    ]
