# Generated by Django 2.2.7 on 2019-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcontent', '0002_auto_20191211_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrip',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, '문화유적'), (2, '랜드마크'), (3, '거리'), (4, '공원'), (5, '박물관'), (6, '종교'), (7, '자연'), (8, '시장'), (9, '교통'), (10, '공공'), (11, 'Place')], verbose_name='구분'),
        ),
    ]
