# Generated by Django 2.2.7 on 2019-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcontent', '0003_auto_20191211_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='artrip',
            name='share',
            field=models.BooleanField(default=True),
        ),
    ]
