# Generated by Django 2.2.7 on 2019-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcontent', '0004_artrip_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrip',
            name='share',
            field=models.BooleanField(default=True, verbose_name='공개여부'),
        ),
    ]
