# Generated by Django 2.2.7 on 2019-12-16 08:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcontent', '0005_auto_20191211_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameko', models.CharField(max_length=40, null=True, verbose_name='장소명(한국어)')),
                ('nameeng', models.CharField(max_length=40, null=True, verbose_name='장소명(영어)')),
                ('nameven', models.CharField(max_length=40, null=True, verbose_name='장소명(베트남어)')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='위치')),
                ('artrip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcontent.ARTrip', verbose_name='ARTrip')),
            ],
            options={
                'verbose_name': 'AR 위치',
                'verbose_name_plural': 'AR 위치',
                'db_table': 'arlocation',
            },
        ),
    ]
