# Generated by Django 2.2.7 on 2019-12-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcontent', '0007_auto_20191216_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='arc/%Y/%m/%d', verbose_name='AR File'),
        ),
    ]
