# Generated by Django 2.2.7 on 2020-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcontent', '0008_auto_20191217_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrip',
            name='category',
            field=models.CharField(choices=[('Cultural-Heritage', '문화유적'), ('Landmark', '랜드마크'), ('Street', '거리'), ('Park', '공원'), ('Museum', '박물관'), ('Religion', '종교'), ('Nature', '자연'), ('Market', '시장'), ('Traffic', '교통'), ('Public', '공공'), ('Place', '장소')], max_length=64, verbose_name='구분'),
        ),
    ]
