# Generated by Django 2.2.7 on 2020-02-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0038_auto_20200123_1535'),
        ('arcontent', '0009_auto_20200105_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='artrip',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.City', verbose_name='City'),
        ),
    ]
