# Generated by Django 2.2.7 on 2019-11-20 03:23

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmall',
            name='categorymedium',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='categorylarge', chained_model_field='categorylarge', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CMedium'),
        ),
    ]
