# Generated by Django 2.2.7 on 2019-11-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20191120_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmall',
            name='name',
            field=models.CharField(max_length=50, verbose_name='categorySmall'),
        ),
    ]
