# Generated by Django 2.2.7 on 2019-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191120_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptest',
            name='choices1',
            field=models.CharField(choices=[('EatDrink', '먹다/마시다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], max_length=50, verbose_name='choices Large'),
        ),
    ]
