# Generated by Django 2.2.7 on 2019-11-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191120_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptest',
            name='categorylarge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CLarge'),
        ),
    ]
