# Generated by Django 2.2.7 on 2019-11-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_tmptest_categorylarge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptest',
            name='categorymedium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CMedium'),
        ),
    ]
