# Generated by Django 2.2.7 on 2019-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_tmptest_categorymedium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptest',
            name='choices1',
            field=models.CharField(choices=[('Eat', '먹다'), ('Drink', '마시다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], max_length=50, verbose_name='choices Large'),
        ),
        migrations.CreateModel(
            name='TmpTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tmptest', models.ManyToManyField(null=True, to='common.TmpTest')),
            ],
        ),
    ]
