# Generated by Django 2.2.7 on 2019-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20191122_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptest',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
