# Generated by Django 2.2.7 on 2019-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_tmptest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptest',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
