# Generated by Django 2.2.7 on 2019-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20191122_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptag',
            name='tmptest',
            field=models.ManyToManyField(to='common.TmpTest'),
        ),
    ]
