# Generated by Django 2.2.7 on 2019-12-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20191205_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='clarge',
            options={'verbose_name': '대분류', 'verbose_name_plural': '대분류'},
        ),
        migrations.AlterModelOptions(
            name='cmedium',
            options={'verbose_name': '중분류', 'verbose_name_plural': '중분류'},
        ),
        migrations.AlterModelOptions(
            name='csmall',
            options={'verbose_name': '소분류', 'verbose_name_plural': '소분류'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='clarge',
            table='clarge',
        ),
        migrations.AlterModelTable(
            name='cmedium',
            table='cmedium',
        ),
        migrations.AlterModelTable(
            name='csmall',
            table='csmall',
        ),
    ]
