# Generated by Django 2.2.7 on 2020-01-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20191205_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='clarge',
            name='nameeng',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='clarge',
            name='nameven',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='cmedium',
            name='nameeng',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='cmedium',
            name='nameven',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='csmall',
            name='nameeng',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='csmall',
            name='nameven',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='clarge',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cmedium',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='csmall',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
