# Generated by Django 2.2.7 on 2020-03-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20200106_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameko', models.CharField(max_length=128)),
                ('nameeng', models.CharField(max_length=128)),
                ('nameven', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'PinEat',
                'ordering': ('nameko',),
            },
        ),
        migrations.CreateModel(
            name='PinDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameko', models.CharField(max_length=128)),
                ('nameeng', models.CharField(max_length=128)),
                ('nameven', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'PinEat',
                'ordering': ('nameko',),
            },
        ),
        migrations.CreateModel(
            name='PinEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameko', models.CharField(max_length=128)),
                ('nameeng', models.CharField(max_length=128)),
                ('nameven', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'PinEat',
                'ordering': ('nameko',),
            },
        ),
        migrations.CreateModel(
            name='PinFun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameko', models.CharField(max_length=128)),
                ('nameeng', models.CharField(max_length=128)),
                ('nameven', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'PinEat',
                'ordering': ('nameko',),
            },
        ),
    ]
