# Generated by Django 2.2.7 on 2020-03-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_pinbuy_pindrink_pineat_pinfun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinbuy',
            options={'ordering': ('nameko',), 'verbose_name': 'PinBuy', 'verbose_name_plural': 'PinBuy'},
        ),
        migrations.AlterModelOptions(
            name='pindrink',
            options={'ordering': ('nameko',), 'verbose_name': 'PinDrink', 'verbose_name_plural': 'PinDrink'},
        ),
        migrations.AlterModelOptions(
            name='pineat',
            options={'ordering': ('nameko',), 'verbose_name': 'PinEat', 'verbose_name_plural': 'PinEat'},
        ),
        migrations.AlterModelOptions(
            name='pinfun',
            options={'ordering': ('nameko',), 'verbose_name': 'PinFun', 'verbose_name_plural': 'PinFun'},
        ),
    ]
