# Generated by Django 2.2.7 on 2020-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20200325_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptest',
            name='choices1',
            field=models.CharField(choices=[('Eat', '먹다'), ('Drink', '마시다'), ('Fun', '놀다'), ('Sleep', '자다'), ('Buy', '사다')], max_length=50, verbose_name='choices Large'),
        ),
    ]
