# Generated by Django 2.2.7 on 2020-04-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20200403_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinbuy',
            name='ordering',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select order'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='pindrink',
            name='ordering',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select order'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='pineat',
            name='ordering',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select order'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='pinfun',
            name='ordering',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select order'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
    ]
