# Generated by Django 2.2.7 on 2020-04-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20200403_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinbuy',
            options={'ordering': ('ordering',), 'verbose_name': 'PinBuy', 'verbose_name_plural': 'PinBuy'},
        ),
        migrations.AlterModelOptions(
            name='pindrink',
            options={'ordering': ('ordering',), 'verbose_name': 'PinDrink', 'verbose_name_plural': 'PinDrink'},
        ),
        migrations.AlterModelOptions(
            name='pineat',
            options={'ordering': ('ordering',), 'verbose_name': 'PinEat', 'verbose_name_plural': 'PinEat'},
        ),
        migrations.AlterModelOptions(
            name='pinfun',
            options={'ordering': ('ordering',), 'verbose_name': 'PinFun', 'verbose_name_plural': 'PinFun'},
        ),
    ]
